name: Publish Docker image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: noureldinelabyad/octopus:latest
        build-args: |
         CONVEX_DEPLOY_KEY=${{ secrets.CONVEX_DEPLOY_KEY }}
         EDGE_STORE_ACCESS_KEY=${{ secrets.EDGE_STORE_ACCESS_KEY }}
         EDGE_STORE_SECRET_KEY=${{ secrets.EDGE_STORE_SECRET_KEY }}
         NEXT_PUBLIC_CONVEX_URL=${{ secrets.NEXT_PUBLIC_CONVEX_URL }}
         NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
         CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }}

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Verify Azure Login
      run: |
        az account show

    - name: Deploy to Azure Web App
      id: deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: myoctopus
        slot-name: production
        images: noureldinelabyad/octopus:latest

    - name: Build and push container image to registry
      uses: azure/container-apps-deploy-action@v2
      with:
        appSourcePath: ${{ github.workspace }} 
        registryUrl: docker.io
        registryUsername: ${{ secrets.OCTOPUS_REGISTRY_USERNAME }}
        registryPassword: ${{ secrets.OCTOPUS_REGISTRY_PASSWORD }}
        containerAppName: octopus
        resourceGroup: octopus
        imageToBuild: noureldinelabyad/octopus:latest
