name: Trigger auto deployment for octopus

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/octopus-AutoDeployTrigger-b24bee59-2761-43a4-8d85-eab250482286.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        build-args: |
        CONVEX_DEPLOY_KEY=${{ secrets.CONVEX_DEPLOY_KEY }}
        EDGE_STORE_ACCESS_KEY=${{ secrets.EDGE_STORE_ACCESS_KEY }}
        EDGE_STORE_SECRET_KEY=${{ secrets.EDGE_STORE_SECRET_KEY }}
        NEXT_PUBLIC_CONVEX_URL=${{ secrets.NEXT_PUBLIC_CONVEX_URL }}
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
        CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }}
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Verify Azure Login
        run: |
          az account show

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: docker.io
          registryUsername: ${{ secrets.OCTOPUS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.OCTOPUS_REGISTRY_PASSWORD }}
          containerAppName: octopus
          resourceGroup: octopus
          imageToBuild: noureldinelabyad/octopus:${{ github.sha }}
       